language: node_js

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

sudo: false

notifications:
  slack: convertigo:tcjIiQJek1NZwdPs5mF7wu5c
  email:
    recipients:
      - charlesg@convertigo.com
      - nicolasa@convertigo.com
    on_success: change # default: change
    on_failure: change # default: always

node_js:
  - '6'

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - export CHROME_BIN=chromium-browser

before_script:
  - npm prune

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start